README.md
package.json
pnpm-lock.yaml
src/background/index.ts
src/manifest.ts
views/popup/Popup.vue

The `webextension-polyfill-ts` has been **[deprecated](https://www.npmjs.com/package/webextension-polyfill-ts)**, and it [recommends](https://github.com/Lusito/webextension-polyfill-ts#migration-guide-from-webextension-polyfill-ts) to use `@types/webextension-polyfill`.

refactor: migrate to webextension-polyfill

---

src/background/index.ts

When closing a tab, the `previousTabId` point to a non-exist tab, and then the `browser.tabs.get` will throw an error.

fix: capture example error

---

package.json
pnpm-lock.yaml
scripts/utils.ts
tsup.config.ts
vite.config.ts

Enable sourcemap in dev mode for a better debug experience.
Minify(without mangle) code in production mode.
Relevance:
* https://github.com/antfu/vitesse-webext/pull/7
* https://github.com/antfu/vitesse-webext/issues/8

feat: enable sourcemap in dev mode, minify code in production

---

scripts/prepare.ts

Modules are only evaluated once so the script was always using a "stale" version of `getManifest` (the one that got loaded during its initialization). By removing that entry from the `require.cache` I allow this module to be re-executed whenever it changes and thus a new, fresh, version of `getManifest` has a chance to be executed.
⚠️ This simplistic solution has a caveat - dependencies of `manifest.ts` won't be reloaded so technically you can still end up with stale manifests. I have wanted to avoid bundling this and I think that this will work for the majority of use cases - if you have a better idea I'm open to revisiting this.

fix: reload manifest.ts module on watch

---

scripts/prepare.ts

https://github.com/antfu/vitesse-webext/blob/01de819b87ae1efb794acb31ccdfbbf5926cf090/scripts/prepare.ts#L28-L30
delete cache is unnecessary any more.

fix: remove delete cache statement

---

shim.d.ts
src/background/main.ts

`onMessage`'s call signature was fixed in https://github.com/antfu/webext-bridge/commit/127395fc4ab058139c6b7826b8966a0102b5bbe9#diff-f200c59206c76dbdfbf32fc10332254fefa285b93bb6abcf57ab84b0013d45d5R10

fix: ts not assignable

---

vite.config.content.ts

Vite watch only triggered a re-build when files in `build.watch.include` changed. That means changes in shared logic outside of those globs were not detected despite being in the dependency tree.
Passing in an empty object and not defining `include` let rollup automatically determine the exact files in the dependency tree that it should watch.
This now rebuilds on any change that are imported.

fix: unspecify includes in contentscript watch

---

package.json
pnpm-lock.yaml
src/composables/useStorageLocal.ts
src/logic/storage.ts

Update `@vueuse/core` to be able to utilize `useStorageAsync` and create a wrapper around `storage.local` from `webextension-polyfill`.

fix: use `storage.local` instead of `Window.localstorage`

---

package.json
pnpm-lock.yaml

Older versions had some errors in type declarations and needed to be updated, such as mainfest's `commands` field.

chore: update `@types/webextension-polyfill` version

---

scripts/utils.ts
vite-mv3-hmr.ts

Dev mode of MV3 fails on Windows due to illegal colons `:` in paths, e.g., `/@fs/C:/` or `/@id/plugin-vue:export-helper`
This PR removes the `C:/` and replaces other colons in paths and `from` import fields with a period
Addresses one of the issues raised [here](https://github.com/antfu/vitesse-webext/issues/59) in [this comment](https://github.com/antfu/vitesse-webext/issues/59#issuecomment-1134116651)
Checked on Windows and a Mac, Windows seems to be working fine, Mac has an `unplugin-icons` error on rebuild (might be an issue with it not knowing about `@id` prefix), but this error is also present without this PR

remove illegal colons in path names on Windows

---

vite.config.content.ts
vite.config.ts

Removed two lines which are re-defining `plugins` key-value pair that was passed from `sharedConfig` by spread operator.

refactor: deleted redundant lines.

---

src/logic/storage.ts

We don't need to set `listenToStorageChanges: true` as it's already by default. 
`useStorageLocal` use vueUse `useStorageAsync` under the hood. [Here the default value in useStorage](https://github.com/vueuse/vueuse/blob/main/packages/core/useStorage/index.ts#L128).

chore: remove `listenToStorageChanges: true`. It's true by default.

---

package.json

> vitesse-webext@0.0.1 clear C:\Users\willi\code\extensions\vitesse-webext
> rimraf --glob extension/dist extension/manifest.json extension.* script
Currently, running `pnpm dev` or `pnpm build` scripts fail with the following error:
```sh
$ pnpm dev
> vitesse-webext@0.0.1 dev C:\Users\willi\code\extensions\vitesse-webext
> npm run clear && cross-env NODE_ENV=development run-p dev:*
> vitesse-webext@0.0.1 clear
> rimraf extension/dist extension/manifest.json extension.*
Error: Illegal characters in path.
at pathArg (C:\Users\willi\code\extensions\vitesse-webext\node_modules\.pnpm\rimraf@4.3.0\node_modules\rimraf\dist\cjs\src\path-arg.js:45:33)
at C:\Users\willi\code\extensions\vitesse-webext\node_modules\.pnpm\rimraf@4.3.0\node_modules\rimraf\dist\cjs\src\index.js:40:80
at Array.map …
```

fix(pkg): add --glob flag to clear script

---

package.json

The `build:background` is missing in `build` script.
maybe we can simplify this later.

fix: add build:background to build workflow

---

src/manifest.ts
vite.config.background.ts

change the extension of background script to .mjs, as it's in esm format.
close #128

fix: change background script to .mjs extension

---

package.json
scripts/utils.ts
src/manifest.ts

Firefox doesn't support `background.service_worker` and wants `background.scripts` in manifest v3 version

fix: support firefox background script

---

.gitpod.Dockerfile
.gitpod.yml
README.md

This PR adds the ability to develop `vitesse-webext` project in the cloud using Gitpod.
You can try it here:
https://gitpod.io/#https://github.com/antfu/vitesse-webext/pull/161

Adding an option to develop in the cloud using Gitpod

---

scripts/prepare.ts

it should be localhost as expected, but the host was trimmed, not intuitive 🤔:
https://github.com/antfu/vitesse-webext/blob/713d7ee0318dfcb88ade3c983919fc828c39ef66/vite.config.ts#L84
close #156

fix: use localhost as base in dev mode

---

.vscode/settings.json
src/composables/useWebExtensionStorage.ts

before:
```ts
const storageDemo = useWebExtensionStorage('webext-demo', 'Storage Demo')
//    ^? RemovableRef<"Storage Demo">
```
after:
```ts
const storageDemo = useWebExtensionStorage('webext-demo', 'Storage Demo')
//    ^? RemovableRef<string>
const storageDemo = useWebExtensionStorage('webext-demo', 'Storage Demo' as const)
//    ^? RemovableRef<"Storage Demo">
```

fix: prefer primitive value types in storage

---

src/composables/useWebExtensionStorage.ts

Multiple triggering of reactive data updates by the same function interspersed with asynchronous functions.
Causing multiple triggers of the watch function in a short period of time
- #162 
- [discussions](https://github.com/antfu-collective/vitesse-webext/discussions/180)

fix: reactive storage infinite loop

---

src/manifest.ts

`manifest.side_panel` produces a type error: `Property 'side_panel' does not exist on type 'WebExtensionManifest'.`
we can typecast it as any

ignore typing for `side_panel` in manifest

---

src/composables/useWebExtensionStorage.ts

The inferred type of `storedData[key]` in the changed line is inferred as unknown but the `StorageLikeAsync` expects type as string.

typing for storageInterface.getItem

---

modules.d.ts

In line with https://github.com/vuejs/router/pull/2295 and https://github.com/nuxt/nuxt/pull/28542, this moves to augment `vue` rather than `@vue/runtime` core.
This is now officially recommended [in the docs](https://vuejs.org/api/utility-types.html#componentcustomproperties) and it _must_ be done by all libraries or it will break types for _other_ libraries.

fix: augment correct module

---

src/contentScripts/views/App.vue

use "v-show" to fix the problem of the bottom-right popup being blocked.
When I tried to use it in a simple way, I found an area for improvement...or rather, a bug..
Just like:
Therefore, I am unable to click on the “page number” area as shown in the figure above.
For this reason, I suggest using "v-show" to control the display of the popup.
When I made improvements using v-show, the result was as follows (the area of the popup that was not displayed was already clickable):
#201 
I hope to receive some feedback. Thank you!

use "v-show" to control the display of the popup

---

src/composables/useWebExtensionStorage.ts
src/logic/storage.ts

During plugin initialization, it is often necessary to read the user's cached configuration.
Since the plugin storage read is asynchronous, the initialization reads the default value, not the cached value. So we need to wait for `storage.local.get` to return the value asynchronously, and then execute the subsequent logic.
After that, we can do this...
```
// logic.ts
export const { data: storageDemo, dataReady: storageDemoReady } = useWebExtensionStorage('webext-demo', true)
```
```
// background.ts
import { storageDemoReady } from './logic'
storageDemoReady.then((val) => {
if (val) {
browser.webNavigation.onBeforeNavigate.addListener(navigateListener)
}
})
```

feat: support storage data ready promise

---

package.json
pnpm-lock.yaml

This PR updates `@ffflorian/jszip-cli` from version 3.7.1 to 3.8.5 to fix an issue with the `pack:zip` script failing to create the extension ZIP file.
The error occurs when the package tries to read files in the extension directory:
`TypeError: fs.lstat is not a function
at BuildService.checkEntry (file:///Users/.../node_modules/.pnpm/@ffflorian+jszip-cli@3.7.1_typescript@5.5.4/node_modules/@ffflorian/jszip-cli/dist/BuildService.js:118:33)`
- The error affects the `pnpm run pack:zip` command which is critical for packaging the extension
- The issue appears to be related to how the package handles file system operations
- The error occurs consistently with version 3.7.1 but is resolved in 3.8.5

chore(deps): update @ffflorian/jszip-cli to ^3.8.5
