antfu-collective/vitesse-webext

package.json

Reverts antfu/vitesse-webext#7
Close #8

Revert "feat: minify for production"

---

.gitignore
package.json
pnpm-lock.yaml

feat: add build:crx, pack extension to extension.crx

feat: add build:crx, pack extension to extension.crx

---

README.md

fix: readme layout error

---

src/background/contentScriptHMR.ts
src/env.ts

chore: add `isForbiddenUrl` to filter the url injected by contentscript hmr

feat: add `isForbiddenUrl` to filter the url injected by contentscript hmr

---

vite.config.ts

fix: relative to assets dir

---

vite.config.ts

https://github.com/antfu/vitesse-webext/issues/35#issuecomment-927121464

fix: vite config base

---

package.json
pnpm-lock.yaml
vite.config.content.ts

fix: change lib output mode

---

tsconfig.json

`strictNullChecks` is included in `strict` option.
https://www.typescriptlang.org/tsconfig#strictNullChecks

fix: remove a redundant strictNullChecks of tsconfig.json

---

package.json
pnpm-lock.yaml
vite.config.ts

fix: auto import webextension-polyfill

---

.vscode/extensions.json

update volar id

---

tsconfig.json

volar needs "jsx": "preserve" in tsconfig

---

vite-mv3-hmr.ts

Check this [comment](https://github.com/antfu/vitesse-webext/issues/59#issuecomment-1167439604)

fix: file loading issue

---

README.md

docs: update Volta logo

---

README.md

docs: fix UnoCSS in readme

---

vite.config.content.ts

fix Vite 3.0.x - library mode not working
https://github.com/vitejs/vite/issues/9320
https://github.com/vitejs/vite/issues/9186

fix vite@3+ library mode not working

---

src/manifest.ts

1. remove useless comment
2. fix content_scripts don't work in dev

fix: content_scripts don't work in dev

---

src/manifest.ts

fix: https://github.com/antfu/vitesse-webext/issues/126
https://github.com/antfu/vitesse-webext/issues/126

fix: adjust manifest config based on the mv3

---

package.json
src/background/index.html
src/manifest.ts
vite.config.background.ts
vite.config.ts

- fix hmr problem caused by https://github.com/antfu/vitesse-webext/pull/124
I test it in chrome, works well.

fix: background build with hmr

---

src/manifest.ts

Permission `http://*/`/`https://*/` is unknown or URL pattern is malformed.

fix: remove malformed URL pattern

---

e2e/basic.spec.ts
e2e/fixtures.ts
package.json
playwright.config.ts
pnpm-lock.yaml
src/contentScripts/index.ts
src/contentScripts/views/App.vue
src/global.d.ts
src/manifest.ts
vite.config.background.ts
vite.config.content.ts
vite.config.ts

Ensure the functionality works using an automated process.

feat: integrate playwright e2e test

---

vite.config.ts

chore: fix deprecated config

---

src/components/README.md

update components readme link
fix https://github.com/antfu-collective/vitesse-webext/issues/172

docs: update components readme

---

src/composables/useWebExtensionStorage.ts

Infinite loop unexpectedly fixed by `await storageInterface.getItem(key)` in the previous [PR](https://github.com/antfu-collective/vitesse-webext/pull/181)
This approach is unreasonable. [Relevant discussion](https://github.com/antfu-collective/vitesse-webext/discussions/180#discussioncomment-9883870)
A better approach would be to pause the `watch` when the `localstroage listen` is triggered
View the commit history, the current code for `useWebExtensionStorage` is based on reference [useStorageAsync](https://github.com/vueuse/vueuse/blob/0c39dd021dacbaaaf3135b0aa171fddb81325880/packages/core/useStorageAsync/index.ts)
`useStorageAsync` here also did not use `pausableWatch` because `browser` mechanism is different from `extension`
```js
// Event not triggered …
```

fix: replace watchWithFilter with pausableWatch

---

package-lock.json
scripts/prepare.ts
src/background/main.ts
src/manifest.ts
src/sidepanel/Sidepanel.vue
src/sidepanel/index.html
src/sidepanel/main.ts
vite.config.mts

Adding the possibility to use the extension with the [chrome sidepanel](https://developer.chrome.com/docs/extensions/reference/api/sidePanel)
fix: https://github.com/antfu-collective/vitesse-webext/issues/174

feat: add sidepanel option

---

README.md

fix typo in README.md - change recommanded to recommended

fix typo - change recommanded to recommended

---

README.md

In README, update the instructions to run the extension for firefox in dev mode

update firefox dev run instructions
